create table acc
(
    ACC_KEY            int auto_increment,
    PT_KEY             int                       default -1                not null,
    ACC_TP_KEY         int                       default -1                not null,
    ACC_STAT_KEY       int                       default -1                not null,
    CCY_KEY            int                       default -1                not null,
    GL_ACC_KEY         int                       default -1                not null,
    GL_ACC_TP_KEY      int                       default -1                not null,
    POS_KEY            int                       default -1                not null,
    ACC_NUM            varchar(255) charset utf8 default ''                not null,
    ACC_ID             varchar(255) charset utf8 default ''                not null,
    ACC_NAME           varchar(255) charset utf8 default ''                not null,
    ACC_SYMBOL         varchar(255) charset utf8 default ''                not null,
    IBAN               varchar(255) charset utf8 default ''                not null,
    OPEN_DATE          date                      default '1000-01-01'      not null,
    ACT_DATE           date                      default '1000-01-01'      null,
    CLOS_DATE          date                      default '1000-01-01'      not null,
    COMP_CODE          varchar(255) charset utf8 default ''                not null,
    SRC_ID             varchar(255) charset utf8 default ''                not null,
    SRC_SYS_ID         varchar(255) charset utf8 default ''                not null,
    DEL_FLAG           smallint                  default 0                 not null,
    INS_PROCESS_ID     varchar(255) charset utf8 default ''                not null,
    INS_DT             datetime                  default CURRENT_TIMESTAMP not null,
    UPD_PROCESS_ID     varchar(255) charset utf8 default ''                not null,
    UPD_DT             datetime                  default CURRENT_TIMESTAMP not null,
    UPD_EFF_DATE       datetime                  default CURRENT_TIMESTAMP not null,
    SRC_UPD_DT         datetime                  default CURRENT_TIMESTAMP not null,
    RN                 int                       default -1                not null,
    PART_ID            varchar(255) charset utf8 as (`SRC_SYS_ID`) stored,
    PL_ID              varchar(255)              default ''                null,
    SECT               varchar(255) charset utf8 default ''                null,
    PER                date                      default '1000-01-01'      null,
    MIN_AMT_CHECK_DATE date                      default '1000-01-01'      null,
    primary key (ACC_KEY, PART_ID),
    constraint unique_src
        unique (SRC_ID, SRC_SYS_ID)
);

