create table entr_trn
(
    ENTR_TRN_KEY             int auto_increment
        primary key,
    SNAP_DATE                date                                                not null,
    ENTR_TRN_TP_KEY          int                       default -1                not null,
    ENTR_TRN_SUB_TP_KEY      int                       default -1                not null,
    ENTR_TRN_STAT_KEY        int                       default -1                not null,
    PMT_SYS_CODE_KEY         int                       default -1                not null,
    PROD_KEY                 int                       default -1                not null,
    AUTH_STAT_KEY            int                       default -1                not null,
    CNL_KEY                  int                       default -1                not null,
    MERCH_KEY                int                       default -1                not null,
    EMP_KEY                  int                       default -1                not null,
    POS_KEY                  int                       default -1                not null,
    POS_TP_KEY               int                       default -1                not null,
    CNTRY_KEY                int                       default -1                not null,
    CARD_TRN_LOC_KEY         int                       default -1                not null,
    ACQR_FIN_INSTN_GRP_KEY   int                       default -1                not null,
    ISSUER_FIN_INSTN_GRP_KEY int                       default -1                not null,
    CCY_KEY                  int                       default -1                not null,
    OCCY_KEY                 int                       default -1                not null,
    MERCH_CODE_KEY           int                       default -1                not null,
    TRML_CNTRY_KEY           int                       default -1                not null,
    ACQR_CNTRY_KEY           int                       default -1                not null,
    TRML_POS_KEY             int                       default -1                not null,
    TRML_LOC                 varchar(255) charset utf8 default ''                null,
    TRML_CITY                varchar(255) charset utf8 default ''                null,
    TRN_AMT                  decimal(19, 3)            default 0.000             null,
    TRN_LCCY_AMT             decimal(19, 3)            default 0.000             null,
    TRN_OCCY_AMT             decimal(19, 3)            default 0.000             null,
    TRN_FX_RX                decimal(10, 6)            default 0.000000          null,
    TRN_VAL_DATE             date                      default '1000-01-01'      null,
    TRN_ENTR_DATE            datetime                  default CURRENT_TIMESTAMP not null,
    TRN_EXPR_DATE            datetime                  default CURRENT_TIMESTAMP not null,
    ENTR_TRN_ID              varchar(255) charset utf8 default ''                null,
    TRN_REF_NUM              varchar(255) charset utf8 default ''                null,
    TRN_AUTH_ID              varchar(255) charset utf8 default ''                null,
    TRN_CARD_MASK            varchar(255) charset utf8 default ''                null,
    TRN_UTIL_CUST_ID         varchar(255) charset utf8 default ''                null,
    TRN_UTIL_VAR_ID          varchar(255) charset utf8 default ''                null,
    TRN_BATCH_ID             varchar(255) charset utf8 default ''                null,
    TRN_STAN_ID              varchar(255) charset utf8 default ''                null,
    TRN_CARD_BIN_ID          varchar(255) charset utf8 default ''                null,
    TRN_CARD_ID              varchar(255) charset utf8 default ''                null,
    ENT_TP_CODE              varchar(255) charset utf8 default ''                null,
    DVC_CODE                 varchar(255) charset utf8 default ''                null,
    ENT_CODE                 varchar(255) charset utf8 default ''                null,
    BRNCH_CODE               varchar(255) charset utf8 default ''                null,
    ACQR_CODE                varchar(255) charset utf8 default ''                null,
    ISSUER_CODE              varchar(255) charset utf8 default ''                null,
    MCC_CODE                 varchar(255) charset utf8 default ''                null,
    TRML_CNTRY_CODE          varchar(255) charset utf8 default ''                null,
    TRML_CODE                varchar(255) charset utf8 default ''                null,
    RET_CODE                 varchar(255) charset utf8 default ''                null,
    TRN_DESCR                varchar(255) charset utf8 default ''                not null,
    CONTLS_TRN_FLAG          int                       default -1                null,
    SRC_ID                   varchar(255) charset utf8 default ''                not null,
    SRC_SYS_ID               varchar(255) charset utf8 default ''                not null,
    UPD_DT                   datetime                  default CURRENT_TIMESTAMP not null,
    UPD_PROCESS_ID           varchar(255) charset utf8 default ''                not null,
    DEL_FLAG                 smallint                  default 0                 not null,
    INS_PROCESS_ID           varchar(255) charset utf8 default ''                not null,
    INS_DT                   datetime                  default CURRENT_TIMESTAMP not null,
    UPD_EFF_DATE             datetime                  default CURRENT_TIMESTAMP not null,
    SRC_UPD_DT               date                      default '1000-01-01'      null,
    RN                       int                       default -1                not null,
    PART_ID                  varchar(255) charset utf8 as (concat(`SRC_SYS_ID`, '_',
                                                                  convert(date_format(`SNAP_DATE`, '%Y%m%d') using utf8))) stored,
    constraint unique_src
        unique (SRC_ID, SRC_SYS_ID)
);

