create table event_trn
(
    EVENT_TRN_KEY        int auto_increment
        primary key,
    SNAP_DATE            date                                                    not null,
    EVENT_TRN_TP_KEY     int                       default -1                    not null,
    EVENT_TRN_SUB_TP_KEY int                       default -1                    not null,
    EVENT_TRN_STAT_KEY   int                       default -1                    not null,
    APPL_KEY             int                       default -1                    not null,
    PROD_KEY             int                       default -1                    not null,
    POS_KEY              int                       default -1                    not null,
    CCY_KEY              int                       default -1                    not null,
    PT_KEY               int                       default -1                    not null,
    CNL_KEY              int                       default -1                    null,
    ACC_KEY              int                       default -1                    not null,
    ACC_NUM              varchar(255) charset utf8 default ''                    not null,
    EMP_KEY              int                       default -1                    not null,
    OPER_CODE            varchar(255) charset utf8 default ''                    not null,
    SC_CODE              varchar(255) charset utf8 default ''                    not null,
    MFO                  varchar(255) charset utf8 default ''                    not null,
    TRN_GRD_DESCR        varchar(255) charset utf8 default ''                    null,
    TRN_AMT              decimal(19, 3)            default 0.000                 null,
    TRN_LCCY_AMT         decimal(19, 3)            default 0.000                 null,
    TRN_FX_RX            decimal(10, 6)            default 0.000000              null,
    TRN_VAL_DATE         datetime                  default '1000-01-01 00:00:00' null,
    TRN_ENTR_DATE        datetime                  default '1000-01-01 00:00:00' null,
    TRN_END_DATE         datetime                  default '1000-01-01 00:00:00' null,
    EVENT_TRN_ID         varchar(255) charset utf8 default ''                    null,
    TRN_ID               varchar(255) charset utf8 default ''                    null,
    EXT_CLOB             varchar(255) charset utf8 default ''                    null,
    EXT_CLOB_XML         varchar(255) charset utf8 default ''                    null,
    SRC_ID               varchar(255) charset utf8 default ''                    not null,
    SRC_SYS_ID           varchar(255) charset utf8 default ''                    not null,
    UPD_DT               datetime                  default CURRENT_TIMESTAMP     not null,
    UPD_PROCESS_ID       varchar(255) charset utf8 default ''                    not null,
    DEL_FLAG             smallint                  default 0                     not null,
    INS_PROCESS_ID       varchar(255) charset utf8 default ''                    not null,
    INS_DT               datetime                  default CURRENT_TIMESTAMP     not null,
    UPD_EFF_DATE         datetime                  default CURRENT_TIMESTAMP     not null,
    SRC_UPD_DT           date                      default '1000-01-01'          null,
    RN                   int                       default -1                    not null,
    PART_ID              varchar(255) charset utf8 as (concat(`SRC_SYS_ID`, '_',
                                                              convert(date_format(`SNAP_DATE`, '%Y%m%d') using utf8))) stored,
    ITEM_KEY             int                       default -1                    null,
    constraint unique_src
        unique (SRC_ID, SRC_SYS_ID)
);

