create table pt
(
    PT_KEY         int auto_increment
        primary key,
    UNI_PT_KEY     int                       default -1                not null,
    CONS_PT_KEY    int                       default -1                not null,
    PT_TP_KEY      int                       default -1                not null,
    PT_STAT_KEY    int                       default -1                not null,
    BUS_SECT_KEY   int                       default -1                not null,
    LGL_FORM_KEY   int                       default -1                not null,
    CNTRY_KEY      int                       default -1                not null,
    LANG_KEY       int                       default -1                not null,
    HOUS_TP_KEY    int                       default -1                not null,
    GENDER_KEY     int                       default -1                not null,
    PERS_ID        varchar(255) charset utf8 default ''                not null,
    COMP_ID        varchar(255) charset utf8 default ''                not null,
    FIRST_NAME     varchar(255) charset utf8                           null,
    FIRST_NAME_LAT varchar(255) charset utf8                           null,
    FAM_NAME       varchar(255) charset utf8                           null,
    FAM_NAME_LAT   varchar(255) charset utf8                           null,
    MID_NAME       varchar(255) charset utf8                           null,
    BUS_NAME       varchar(255) charset utf8                           null,
    BUS_NAME_LAT   varchar(255) charset utf8                           null,
    SHORT_NAME     varchar(255) charset utf8                           null,
    SHORT_NAME_LAT varchar(255) charset utf8                           null,
    IS_INSIDER     varchar(255) charset utf8                           null,
    BRTH_DATE      date                                                null,
    RES_FLAG       int                       default -1                not null,
    BNKR_FLAG      int                       default -1                not null,
    TAX_PAYER_FLAG int                       default -1                not null,
    PEP_FLAG       int                       default -1                not null,
    START_DATE     date                                                null,
    END_DATE       date                                                null,
    PT_ID          varchar(255) charset utf8 default ''                not null,
    SRC_SYS_ID     varchar(255) charset utf8                           not null,
    SRC_ID         varchar(255) charset utf8                           not null,
    DEL_FLAG       smallint                  default 0                 not null,
    INS_PROCESS_ID smallint                  default 0                 not null,
    INS_DT         datetime                  default CURRENT_TIMESTAMP not null,
    UPD_PROCESS_ID smallint                  default 0                 not null,
    UPD_DT         datetime                  default CURRENT_TIMESTAMP not null,
    UPD_EFF_DATE   datetime                  default CURRENT_TIMESTAMP not null,
    SRC_UPD_DT     datetime                  default CURRENT_TIMESTAMP not null,
    RN             int                       default -1                not null,
    PART_ID        varchar(255) charset utf8 as (`SRC_SYS_ID`) stored,
    constraint unique_idx_src_id_src_sys_id
        unique (SRC_ID, SRC_SYS_ID)
);

